import type { RiskCard, Zone } from './types';

export const ZONES: Zone[] = [
  { key: 'sound', label: 'Звук', hint: 'FOH, микрофоны, радиочастоты' },
  { key: 'light', label: 'Свет', hint: 'Сцены, сценарий света, пульты' },
  { key: 'video', label: 'Видео', hint: 'Камеры, режиссура, контент' },
  { key: 'led', label: 'LED', hint: 'Экраны, контент-мэппинг, синхрон' },
  { key: 'stream', label: 'Трансляция', hint: 'CDN, кодеки, резервные каналы' },
  { key: 'registration', label: 'Регистрация', hint: 'QR, стойки, тайм-слоты' },
  { key: 'venue', label: 'Площадка', hint: 'Логистика, доступы, питание' },
  { key: 'staff', label: 'Персонал', hint: 'Брифинг, смены, ответственные' },
];

export const ALL_RISKS: RiskCard[] = [
  { id: 'r1', title: 'Радиомикрофоны конфликтуют по частотам', type: 'sound', weight: 4 },
  { id: 'r2', title: 'Провал громкости на дальних рядах', type: 'sound', weight: 3 },
  { id: 'r3', title: 'Нет плана резервного пульта', type: 'sound', weight: 5 },
  { id: 'r4', title: 'Световые сцены не привязаны к таймингу', type: 'light', weight: 4 },
  { id: 'r5', title: 'Отсутствует дежурный оператор follow-spot', type: 'light', weight: 3 },
  { id: 'r6', title: 'Конфликт DMX-линий', type: 'light', weight: 4 },
  { id: 'r7', title: 'Камеры без согласованного плана кадров', type: 'video', weight: 3 },
  { id: 'r8', title: 'Нарушена синхронизация тайм-кода', type: 'video', weight: 5 },
  { id: 'r9', title: 'Нет превью контента перед эфиром', type: 'video', weight: 2 },
  { id: 'r10', title: 'LED-контент в неверном разрешении', type: 'led', weight: 5 },
  { id: 'r11', title: 'Экран не откалиброван по яркости', type: 'led', weight: 3 },
  { id: 'r12', title: 'Нет резервного медиасервера', type: 'led', weight: 4 },
  { id: 'r13', title: 'Потеря пакетов в аплинке трансляции', type: 'stream', weight: 5 },
  { id: 'r14', title: 'Не проверен backup-интернет', type: 'stream', weight: 4 },
  { id: 'r15', title: 'Неверный аудио-микс для онлайн-аудитории', type: 'stream', weight: 3 },
  { id: 'r16', title: 'Очереди на стойках регистрации', type: 'registration', weight: 3 },
  { id: 'r17', title: 'QR-коды гостей не прогружены офлайн', type: 'registration', weight: 4 },
  { id: 'r18', title: 'Нет отдельной линии для VIP', type: 'registration', weight: 2 },
  { id: 'r19', title: 'Схема загрузки/выгрузки не согласована', type: 'venue', weight: 4 },
  { id: 'r20', title: 'Площадка не готова к экстренному сценарию', type: 'venue', weight: 5 },
  { id: 'r21', title: 'Нет плана расстановки навигации', type: 'venue', weight: 2 },
  { id: 'r22', title: 'Не назначен ответственный по backstage', type: 'staff', weight: 4 },
  { id: 'r23', title: 'Персонал не прошёл единый брифинг', type: 'staff', weight: 5 },
  { id: 'r24', title: 'Смены волонтёров пересекаются', type: 'staff', weight: 3 },
  { id: 'r25', title: 'Резервные батареи для петличек не подписаны', type: 'sound', weight: 2 },
  { id: 'r26', title: 'Световые фермы без итоговой проверки', type: 'light', weight: 5 },
  { id: 'r27', title: 'Графика спикеров не утверждена', type: 'video', weight: 2 },
  { id: 'r28', title: 'LED-стена и проекция конфликтуют по цвету', type: 'led', weight: 3 },
  { id: 'r29', title: 'Нет fallback-сцены при падении эфира', type: 'stream', weight: 4 },
  { id: 'r30', title: 'Неполная база бейджей в день события', type: 'registration', weight: 3 },
  { id: 'r31', title: 'Отсутствует схема проходов для поставщиков', type: 'venue', weight: 3 },
  { id: 'r32', title: 'Критичные контакты подрядчиков не в едином чате', type: 'staff', weight: 4 },
  { id: 'r33', title: 'Резервный сабмикшер не подключён', type: 'sound', weight: 3 },
  { id: 'r34', title: 'Не выверен баланс холодного/тёплого света', type: 'light', weight: 2 },
  { id: 'r35', title: 'Не задан план смены презентаций на сцене', type: 'video', weight: 3 },
  { id: 'r36', title: 'Контент LED не проверен на артефакты', type: 'led', weight: 4 },
];
